// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kommande_auth_backend.Data;

#nullable disable

namespace kommande_auth_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119145924_UserTypeDatabase3")]
    partial class UserTypeDatabase3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("kommande_auth_backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("kommande_auth_backend.Models.BasicUser", b =>
                {
                    b.HasBaseType("kommande_auth_backend.Models.User");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("BasicUser");
                });

            modelBuilder.Entity("kommande_auth_backend.Models.GoogleUser", b =>
                {
                    b.HasBaseType("kommande_auth_backend.Models.User");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("GoogleUser");
                });
#pragma warning restore 612, 618
        }
    }
}
